repos:
  - repo: https://github.com/psf/black
    rev: 21.5b2  # Use the ref you want to point at
    hooks:
      - id: black
        language_version: python3.10  # Update this line to match your Python version
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]